### ISSUE TITLE
panic: ./app flag redefined: graceful

### ISSUE THREAD

**Issue by tomsherrod** [snagles/docker-registry-manager#95] opened 2017-11-08 21:08 UTC
Interesting registry manager.
Before making any tweaks, pulled it down and ran go build successfully.
Running the app results in a panic though:
panic: ./app flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42005a180, 0xde0fa0, 0xe47274, 0xab3d70, 0x8, 0xac5c36, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:793 +0x5e1
flag.BoolVar(0xe47274, 0xab3d70, 0x8, 0xc42004bf00, 0xac5c36, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:572 +0x72
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init.0()
        /home/ubuntu/gowork/src/github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace/grace.go:93 +0x60
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init()
        <autogenerated>:1 +0x89
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego.init()
        <autogenerated>:1 +0x73
github.com/snagles/docker-registry-manager/app/routers.init()
        <autogenerated>:1 +0x44
main.init()
        <autogenerated>:1 +0x8e

Any suggestions on what I may be doing wrong?

**Comment by splisson-altair** [comment] 2017-11-09 01:31
Define your GOPATH env var where you want to have your go files.
in $GOPATH/src/github.com . , git clone the repository
Then from docker-registry-manager/app:
go get -d .
go build .
then run  ./app --port 8080 --log warn --ttl 2m

**Comment by snagles** [comment] 2017-11-09 02:27
Hi Tom,

Go ahead and give what @splisson-altair mentioned a try. If that does not work let me know and I'll create a few binary releases for you architecture. If you have Docker I would definitely recommend that method if you don't have a go development environment setup.

Thanks for jumping in @splisson-altair.

**Comment by tomsherrod** [comment] 2017-11-13 15:19
Followed those instructions. Same result.
~/gowork/src/github.com/docker-registry-manager/app$ ./app --port 8080 --log warn --ttl 2m
./app flag redefined: graceful
panic: ./app flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42005c180, 0xde9f60, 0xe501f4, 0xab3be7, 0x8, 0xac5a9c, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:793 +0x5e1
flag.BoolVar(0xe501f4, 0xab3be7, 0x8, 0xc42004df00, 0xac5a9c, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:572 +0x72
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init.0()
        /home/rdcadmin/gowork/src/github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace/grace.go:93 +0x60
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init()
        <autogenerated>:1 +0x89
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego.init()
        <autogenerated>:1 +0x73
github.com/snagles/docker-registry-manager/app/routers.init()
        <autogenerated>:1 +0x44
main.init()
        <autogenerated>:1 +0x8e

@snagles I'm hoping to make some tweaks (ie not checking github, etc) once I figure out how to get it built, in addition to learning some go! I successfully got the docker one running, no issues.

**Comment by snagles** [comment] 2017-11-13 17:07
@tomsherrod I imagine the error is because some of the dependencies are not vendorized, leading to what you are experiencing. I was able to recreate the error when starting with an empty gopath and running a go get for the latest dependencies.

I'll fix this in #92

**Comment by snagles** [comment] 2017-11-14 17:11
Hi Tom, 

Go ahead and give it a try now, I've merged the vendoring changes into the develop branch if you would like to test there.

I had to remove some tests due to dependency mismatch problems to accomplish this, so once I get those resolved I'll merge develop to master.

**Comment by tomsherrod** [comment] 2017-11-21 14:34
Hi,
Deleted everything under the go work directory.
git cloned and checked out develop.
go get -d .
go build .
./app --port 8080 --log warn --ttl 2m
./app flag redefined: graceful
panic: ./app flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42005c060, 0xdb8f20, 0xe1eab4, 0xa9933d, 0x8, 0xaab068, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:793 +0x5e1
flag.BoolVar(0xe1eab4, 0xa9933d, 0x8, 0xc42004df00, 0xaab068, 0x21)
        /usr/lib/go-1.9/src/flag/flag.go:572 +0x72
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init.0()
        /home/rdcadmin/gowork/src/github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace/grace.go:93 +0x60
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego/grace.init()
        <autogenerated>:1 +0x89
github.com/snagles/docker-registry-manager/vendor/github.com/astaxie/beego.init()
        <autogenerated>:1 +0x73
github.com/snagles/docker-registry-manager/app/routers.init()
        <autogenerated>:1 +0x44
main.init()
        <autogenerated>:1 +0x84

Something still unhappy?

**Comment by snagles** [comment] 2017-11-22 01:48
Hi Tom,

There must be something going on with beego init getting called twice, once from the vendored package and once from the one that has been retrieved via "go get". I have not been able to determine why some calls are seemingly ignoring the vendored version, and move on to the gopath one. 

You should not need to run go get, as the vendored directory should have everything self contained. I moved the vendor directory to within the app folder and that seems to have fixed it. I suspect the mismatch was caused by the vendor directory not be placed in the same directory as main.go . 

Try these steps to confirm (this was how I was able to recreate it previously):

-  remove `~/gowork/src/github.com/astaxie/beego` and `~/gowork/src/github.com/snagles`
- `mkdir -p ~/gowork/src/github.com/snagles`
- `export GOPATH=~/gowork`
- `cd  ~/gowork/src/github.com/snagles`
- `git clone https://github.com/snagles/docker-registry-manager.git && cd docker-registry-manager`
- `git checkout develop`
- `cd ~/gowork/src/github.com/snagles/docker-registry-manager/app`
- `go build . && ./app`

Let me know how it works, this is an interesting case...

**Comment by tomsherrod** [comment] 2017-11-25 16:57
Success! The app ran once I followed the last set of directions.

Thanks,
Tom

**Closed** 2017-11-26 13:58 UTC
